export const ERRORS_CONSTANTS = {
    DB: {
        23505: (entityName: string): string => `${entityName} already exists.`
    },
    CODES: {
        INVALID_CREDENTIALS: 'ERROR.INVALID_CREDENTIALS',
        INVALID_CODE_ACTIVATION: 'ERROR.INVALID_CODE_ACTIVATION',
        USER_NOT_FOUND: 'ERROR.USER_NOT_FOUND',
        USER_NOT_ACTIVATE_PHONE: 'ERROR.USER_NOT_ACTIVATE_PHONE',
        USER_NOT_ACTIVATE_EMAIL: 'ERROR.USER_NOT_ACTIVATE_EMAIL',
        USER_ALREADY_EXISTS: 'ERROR.USER_ALREADY_EXISTS'
    }
};